### PR TITLE
"Optimize" ship detection

### PR DESCRIPTION
**Pull request by HyperSoop**
This simple change seems to cut down on detection time from 7-9ms to 3-5ms, aka makes it twice as fast

### CODE REVIEW

**Comment by HyperSoop** [comment]
i failed git

**Comment by trainb0y** [comment]
one does not fail git
git fails you

**Comment by HyperSoop** [comment]
yes

**Comment by trainb0y** [comment]
the detection stuff is pain and suffering
aaaaaaa

**Pull request merged**
